
// YOU WILL NEED TO MAKE THESE MATCH THE REAL DB SCHEMA

export default interface DataSample {
    id: number;
    time: Date;
    freq: number;
    Vab: number;
    Vbc: number;
    Vca: number;
    Van: number;
    Vbn: number;
    Vcn: number;
    pf: number;
    'Real Power': number;
    'Reactive Power': number;
    'Apparent Power': number;
    Ia: number;
    Ib: number;
    Ic: number;
    'P2 Ctrl Method': number;
    'P2 throttle setpt': number;
    'P2 current setpt': number;
    'P2 power setpt': number;
    'P2 voltage setpt': number;
    'P2 Vmax Limit': number;
    'P2 Vmin Limit': number;
    'P2 Dischg PWR limit': number;
    'P2 Chrg PWR limit': number;
    'P2 Current limit': number;
    'P2 Voltage': number;
    'P2 Power': number;
    'P2 Current': number;
    'P3 Ctrl Method': number;
    'P3 throttle setpt': number;
    'P3 current setpt': number;
    'P3 power setpt': number;
    'P3 voltage setpt': number;
    'P3 Vmax Limit': number;
    'P3 Vmin Limit': number;
    'P3 Dischg PWR limit': number;
    'P3 Chrg PWR limit': number;
    'P3 Current limit': number;
    'P3 Voltage': number;
    'P3 Power': number;
    'P3 Current': number;
    'Avg PM Temp': number;
    'AC PM Temp': number;
    'DC PM Temp': number;
    'Onboard Temp': number;
    'Fan Speed': number;
    'System Status': number;
    'System Power': number;
    'Grid Support Status': number;
    'Link Peak Voltage': number;
    'Link Peak Current': number;
    'Grid Level Status': number;
    'Grid Stop Status': number;
    'Pack P2 Voltage': number;
    'Pack P3 Voltage': number;
}